# Generated by Django 2.1.5 on 2019-03-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('xaxis', models.CharField(max_length=250)),
                ('yaxis', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Xaxisdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(help_text='Enter a Data..', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Yaxisdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(help_text='Enter a Data..', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='chart',
            name='xaxisdata',
            field=models.ManyToManyField(help_text='Select a Options', to='article.Xaxisdata'),
        ),
        migrations.AddField(
            model_name='chart',
            name='yaxisdata',
            field=models.ManyToManyField(help_text='Select a Options', to='article.Yaxisdata'),
        ),
    ]
